- hosts : centos

  tasks:
    - name: install web server
      yum:
        name: httpd
        state: present
    - name: copy file
      copy:
        src: ../index.html
        dest: /var/www/html
    - name: restart service
      systemd:
        name: httpd
        state: restarted
    - name: allow firewall
      firewalld:
        service: http
        permanent: yes
        immediate: yes
        state: enabled
